### ISSUE TITLE
func testJson() async throws crashes app made with UIKit

### ISSUE THREAD

**Issue by DhrumilBankABC** [kewlbear/YoutubeDL-iOS#10]
Hello, Thank you for the amazing library
`func testJson() async throws {` this function runs properly in demo project
Demo project is based on SwiftUI while i am using this library in UIKit project.

In my project when i try to call the same function app is getting crashed

<string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
testJson() info [youtube] Extracting URL: https://www.youtube.com/watch?v=dB7d89-YHjM
testJson() info [youtube] dB7d89-YHjM: Downloading webpage
testJson() info [youtube] dB7d89-YHjM: Downloading android player API JSON
Popen.__init__: <yt_dlp.utils.Popen object at 0x1606866b0> (['ffmpeg', '-bsfs'],)
Popen.communicate: <yt_dlp.utils.Popen object at 0x1606866b0> () {'timeout': None}
popenHandler [<yt_dlp.utils.Popen object at 0x1606866b0>, (['ffmpeg', '-bsfs'],)]

Please help me with this i am stuck here
Thank you

**Comment by kewlbear** [comment]
Are there no more console output after that?

**Comment by DhrumilBankABC** [comment]
No

**Comment by DhrumilBankABC** [comment]
@kewlbear could you point me in right direction to make this work in UIKit project?
SwiftUI project seems to working but in UIKit project i am getting above error everytime
thank you

**Comment by DhrumilBankABC** [comment]
@kewlbear i found out the cause of the issue but i am not able to solve it

steps to produce
Create project
Install below mentioned Cocoapods

pod 'MobileVLCKit'
pod 'VLCMediaLibraryKit"

run the app and call testJson() function

you will encounter error like below
`Popen.init: <yt_dlp.utils.Popen object at 0x1606866b0> (['ffmpeg', '-bsfs'],)
Popen.communicate: <yt_dlp.utils.Popen object at 0x1606866b0> () {'timeout': None}
popenHandler [<yt_dlp.utils.Popen object at 0x1606866b0>, (['ffmpeg', '-bsfs'],)]`

if you remove these two pods, testJson() function will execute just fine
do you have any idea why this is happening?
thank you

**Comment by kewlbear** [comment]
I guess you better see https://github.com/arthenica/ffmpeg-kit/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-Application-on-Apple-Platforms.
I don't know how this applies to this package.  Maybe you should use ffmpeg-kit instead of this package.
