### ISSUE TITLE
Crash Py_IsInitialized() EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by dolphinysaru** [kewlbear/YoutubeDL-iOS#14]
Hello. I am using the library well. thank you

As mentioned in the title, a crash occurs in Py_IsInitialized.
An image has been attached.

It operates normally in XCode Debug mode. However, it does not work properly in Release mode. Is there any way to solve this?

![스크린샷 2024-02-06 오전 12 29 55](https://github.com/kewlbear/YoutubeDL-iOS/assets/8189564/5fa63df0-3091-49b1-98a4-78b18f847757)

**Comment by kewlbear** [comment]
Please see #1 and #3.

**Comment by dolphinysaru** [comment]
![스크린샷 2024-02-06 오전 11 35 15](https://github.com/kewlbear/YoutubeDL-iOS/assets/8189564/e099d97d-9c3a-4b0c-a889-231b12f77b26)

I changed the build settings, but the crash still occurs.
Is there any other way? I will also try to find the cause.

**Comment by dolphinysaru** [comment]
I modified it by referring to the sample project.
I changed the Strip style to Debugging and additionally changed the Enable Testability value to Yes.
Thank you
![스크린샷 2024-02-06 오후 2 13 47](https://github.com/kewlbear/YoutubeDL-iOS/assets/8189564/1dc60e98-a5de-484a-a247-4ed43500952e)
