### ISSUE TITLE
File system is read only

### ISSUE THREAD

**Issue by KernelFox0** [kewlbear/YoutubeDL-iOS#15]
When I use the Xcode project provided in this repo it works, but when I add it to my app the python script fails with the error "Errno 30 File System is read-only"

**Comment by kewlbear** [comment]
Can you share backtrace?

**Comment by KernelFox0** [comment]
> Can you share backtrace?

Sure. (Note: I used different arguments for youtubedl but that's not the issue because when I replaced the example args with mine in the [usage example by you](https://github.com/kewlbear/YoutubeDL) it worked normally)

Backtrace and logs:

[backtrace.txt](https://github.com/kewlbear/YoutubeDL-iOS/files/14271076/backtrace.txt)
[logs.txt](https://github.com/kewlbear/YoutubeDL-iOS/files/14271077/logs.txt)

**Comment by kewlbear** [comment]
I guess you need https://github.com/kewlbear/YoutubeDL/blob/6b5e506f78bda7c6cdfb9c24bf0f33b0d8edd58b/YoutubeDL/AppDelegate.swift#L46.

**Comment by KernelFox0** [comment]
> I guess you need https://github.com/kewlbear/YoutubeDL/blob/6b5e506f78bda7c6cdfb9c24bf0f33b0d8edd58b/YoutubeDL/AppDelegate.swift#L46.

That worked! Thank you.
