### ISSUE TITLE
Using yt-dlp instead of Youtube-dl

### ISSUE THREAD

**Issue by sherwinzadeh** [kewlbear/YoutubeDL-iOS#2]
First of all, @kewlbear, thank you for this great tool.

Recently there's been an issue on Youtube-dl where some videos are taking a very long time to download. See:
[https://github.com/ytdl-org/youtube-dl/issues/29326](https://github.com/ytdl-org/youtube-dl/issues/29326)

Users have said that the **[ytl-dlp](https://github.com/yt-dlp/yt-dlp)** fork solves it and I'd like to try it out in YoutubeDL-iOS. What I've done is change:
`	public static let latestDownloadURL = URL(string: "https://github.com/yt-dlp/yt-dlp/releases/latest")!`
I also changed the file name stored locally from `youtube_dl` to `yt-dlp`
The problem I'm getting though is `Python.attemptImport("yt-dlp")` throws an exception:
 **No module named 'yt-dlp'**
(I've tried many other names too)

You can see my attempts in this [fork](https://github.com/sherwinzadeh/YoutubeDL-iOS) in the `yt-dlp` branch. 

Any idea what I'm doing wrong?

**Comment by kewlbear** [comment]
Updated to use yt-dlp.  Thanks for your info!

**Comment by khatri6168** [comment]
Hello @kewlbear.

Thank you for this great tool.

I have one issue the tools are working fine when I test in debug mode.
but when I upload build in TestFlight and check the app is crash in downloadPythonModule or YoutubeDL() 

can you please let me know this is working this tool in live TestFlight. no nee to upload the app in App Store.

Any idea what I'm doing wrong?

**Comment by sherwinzadeh** [comment]
I believe you need to turn off bitcode in order for Python modules to work.

**Comment by khatri6168** [comment]
Hello @sherwinzadeh  Thank you for replay. 

I have off bitcode and upload agin new build bit still it'e crashing not working this in only in TestFlight.

Have you face this type of issue?

**Comment by HamstyDeveloper** [comment]
we have an issue. the build is working in simulator but not working on real device
