### ISSUE TITLE
crash in TestFlight 

### ISSUE THREAD

**Issue by khatri6168** [kewlbear/YoutubeDL-iOS#3]
Hello @kewlbear.

Thank you for this great tool.

I have one issue the tools are working fine when I test in debug mode.
but when I upload build in TestFlight and check the app is crash in downloadPythonModule or YoutubeDL()

can you please let me know this is working this tool in live TestFlight. no nee to upload the app in App Store.

Any idea what I'm doing wrong?

**Comment by kewlbear** [comment]
Try setting STRIP_STYLE=debugging.
