### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cfcor** [kewlbear/YoutubeDL-iOS#4]
First of all, thank you for your work.@kewlbear
When I build my own project using your package, I met this error.Would you like to give me a help
<img width="1386" alt="Screen Shot 2022-03-23 at 23 36 58" src="https://user-images.githubusercontent.com/87554617/159837276-55680515-0c53-4595-8263-201482f4ca1b.png">
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Users/imacroot/Library/Developer/CoreSimulator/Devices/43F22D6E-DFD9-4629-BB1D-812F1373677E/data/Containers/Bundle/Application/05AEF08C-1017-4119-B01A-935C568BEEC9/VideoPlus.app/VideoPlus'
  sys.base_prefix = '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  sys.base_exec_prefix = '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  sys.platlibdir = 'lib'
  sys.executable = '/Users/imacroot/Library/Developer/CoreSimulator/Devices/43F22D6E-DFD9-4629-BB1D-812F1373677E/data/Containers/Bundle/Application/05AEF08C-1017-4119-B01A-935C568BEEC9/VideoPlus.app/VideoPlus'
  sys.prefix = '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  sys.exec_prefix = '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  sys.path = [
    '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3/lib/python39.zip',
    '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3/lib/python3.9',
    '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010fb33e00 (most recent call first):
<no Python frame>

**Comment by kewlbear** [comment]
Looks like a runtime error, not a build error.  In that case make sure to call `PythonSupport.initialize()` before using this package.

**Comment by cfcor** [comment]
Thank you very much, it worked out!
