### ISSUE TITLE
thumbnail api

### ISSUE THREAD

**Issue by cfcor** [kewlbear/YoutubeDL-iOS#5]
I would like to use video thumbnails. But I don't find the api, would you like to give me a help?@kewlbear, thank you very much!

**Comment by kewlbear** [comment]
There is `thumbnail` field in `Info` struct at: https://github.com/kewlbear/YoutubeDL-iOS/blob/33d37dc8f7a84dde1ce0fba0f2bb36c1511b0a10/Sources/YoutubeDL/YoutubeDL.swift.

**Comment by cfcor** [comment]
thank you very much! wish you all the best!

**Comment by cfcor** [comment]
> There is `thumbnail` field in `Info` struct at: https://github.com/kewlbear/YoutubeDL-iOS/blob/33d37dc8f7a84dde1ce0fba0f2bb36c1511b0a10/Sources/YoutubeDL/YoutubeDL.swift.

thank you very much! wish you all the best!
